[tool.poetry]
name = "hermit-python3"
version = "0.1.0"
description = ""
authors = ["zhengweixin <zhengweixin@didiglobal.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
